### PR TITLE
Feature/cf package export local swagger includes transform

### PR DESCRIPTION
**Pull request by ekcrisp**
When providing a swagger definition for AWS::Serverless::Api resource using DefinitionUri you are unable to use cloudformation intrinsic functions. Several users have complained about this. One workaround is using AWS::Include transformation to reference a swagger doc from the inline property DefinitionBody where intrinsic functions can be used. This feature provides the same local file export for swagger documents referenced from an AWS::Include in the DefinitionBody as the existing DefinitionUri file export. Below are links to discussions where this feature has been mentioned.

https://github.com/awslabs/serverless-application-model/issues/160
https://github.com/awslabs/serverless-application-model/issues/8
https://github.com/awslabs/serverless-application-model/issues/345

### CODE REVIEW

**Comment by ekcrisp** [comment]
I opened https://github.com/aws/aws-cli/pull/3454 which covers a broader case than this, will close if that PR is approved

**Comment by stealthycoin** [comment]
Thanks for the PR! @sanathkr can you take a look at this?

**Comment by ekcrisp** [comment]
no longer needed as #3454 was merged

**Comment by banenen** [comment]
Are there any documentation of how to use this?

**Comment by apogiatzis** [comment]
Has this been merged? I was not able to use this feature. My packaged template still translates to DefinitionUri: s3://.... (I am using sam-translator 1.18)

**Pull request closed without merging**
