### PR TITLE
Adding support for skipping automatic property uploads

### PR DESCRIPTION
**Pull request by dtimberlake**
This adds the ability to specify that a resource should not have its property automatically uploaded when run through `aws cloudformation package` if the property is not specified in the original template.

It also adds this functionality to `ApiGatewayRestApiResource`.

This is in response to #2320

### CODE REVIEW

**Comment by sanathkr** [comment]
Looks good to me

**Comment by sanathkr** [comment]
@dtimberlake Can you also update the documentation to reflect this change in behavior @ /awscli/examples/cloudformation/_package_description.rst

**Comment by dtimberlake** [comment]
Documentation has been updated.

**Comment by jamesls** [comment]
Thanks, let me take a look here.

**Comment by sanathkr** [comment]
This looks good to me

**Pull request merged**
