### PR TITLE
Update colorama version

### PR DESCRIPTION
**Pull request by dslackw**

### CODE REVIEW

**Comment by kyleknap** [comment]
Looks fine to me.

**Comment by kyleknap** [comment]
Here is the CHANGELOG for reference: https://github.com/tartley/colorama/blob/master/CHANGELOG.rst

**Comment by kyleknap** [comment]
Actually after some testing. It looks like this version breaks us if you are trying to pipe color:
```
$ aws ec2 describe-instances --color on --output table | less -r
```

I do not think we will be able to take in 0.3.5. Will have to revert it.

**Comment by c22** [comment]
As per #2037 this behavior was not intended behavior of colorama, see [changelog entry](https://github.com/tartley/colorama/blob/master/CHANGELOG.rst) for 0.3.4

**Pull request merged**
