### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by ChrisAHolland**
*Description of changes:*
Doc's pull request. Made the README's grammar more consistent and correct. Very minor changes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ChrisAHolland** [comment]
CC @kyleknap @joguSD @KaibaLopez

**Comment by ChrisAHolland** [comment]
> Thanks for pointing these out!

You're welcome! Excited to hopefully have my PR's merged!

**Comment by ChrisAHolland** [comment]
@KaibaLopez Anything more needed before a merge?

**Comment by kdaily** [comment]
Hi @ChrisAHolland, apologies for the late reply, and thanks again for your contribution. We recently restructured the README and it looks like there's some conflicts. Can you review if there's anything that you suggested to change that is still needed?

One note on something that you suggested. We are going to be more intentional with the use of 'AWS CLI' and `aws-cli` - when referring to something that is not specifically related to the Python package, we will prefer 'AWS CLI'. If it is for the Python package itself, then the package name is fine.

**Comment by ChrisAHolland** [comment]
@kdaily Thanks for the reply! I made the changes and created #5467 because I had an issue with the branch for this PR.
I hope it helps!

**Comment by kdaily** [comment]
Since you opened #5467, I'll close this one now. Thanks!

**Pull request closed without merging**
