### PR TITLE
Added missing --user-attributes flag

### PR DESCRIPTION
**Pull request by aamirmushtaq**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aamirmushtaq** [comment]
Found the flag was missing to add the user attributes
```
➜  /Users/<myuser>/codebase/aws-cli (cognito-documentation-fix) ✔ aws --version
aws-cli/1.16.100 Python/3.7.2 Darwin/18.5.0 botocore/1.12.90

```

**Comment by aamirmushtaq** [comment]
Is this in yet?

**Comment by kdaily** [comment]
Apologies for the delay, @aamirmushtaq. It does look like this change was subsequently fixed, but inadvertently added an extra space. I've rebased your change and we can pull it in to fix that. Thanks!

**Review by justindho — APPROVED** [review]
@aamirmushtaq Thanks for the contribution!

**Pull request merged**
