### PR TITLE
Add --exclude-profile option to eks update-kubeconfig

### PR DESCRIPTION
**Pull request by soggycactus**
*Issue #, if available:*

This PR resolves https://github.com/aws/aws-cli/issues/7087

*Description of changes:*

This PR adds a new option to `aws eks update-kubeconfig` called `exclude-profile`. Currently, when using `update-kubeconfig`, if an AWS profile session is detected the generated kubeconfig will include an `env` block with `AWS_PROFILE` in the user's exec config. Example:

```
users:
- name: arn:aws:eks:region:111222333444:cluster/ExampleCluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - region
      - eks
      - get-token
      - --cluster-name
      - ExampleCluster
      - --output
      - json
      command: aws
      env:
        - name: AWS_PROFILE
          value: <profile-name>
```
This may be undesirable behavior depending on how you manage your AWS credentials. When specifying the `--exclude-profile` option added in this PR, the `env` block will not be added.

Rather than as described in the issue above, I chose to add `exclude-profile` instead of `include-profile` to keep consistent behavior with previous versions of awscli. 

I added a unit test to ensure the option works properly. The test injects an `AWS_PROFILE` environment variable at runtime to simulate an AWS "session" and passes `--exclude-profile` to the command, and asserts that the resulting kubeconfig does _not_ have an `env` block; if `exclude_profile` is set to `False`, the test fails (as it should). 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. I am available to make any changes needed for this PR to be merged.

### CODE REVIEW

**Comment by soggycactus** [comment]
Bumping @stealthycoin @kyleknap @yuxiang-zhang for review 

CC @tim-finnigan

**Comment by soggycactus** [comment]
Hi any updates on this? It's a small non-breaking change and I am also around to address any feedback or changes needed! 

CC @stealthycoin @kyleknap @tim-finnigan @hssyoo

**Comment by tim-finnigan** [comment]
Hi @soggycactus thanks for the PR. I discussed this with @yuxiang-zhang who has been reviewing EKS customization changes and he thinks this looks good. But his other PR involving `update-kubeconfig` will probably need to be prioritized for review first. There is a backlog of issues and PRs to review but we will let you know here when we have any updates.

**Comment by soggycactus** [comment]
Hey @tim-finnigan any updates on this? It's been a few months now

I took a look at #7678 and it looks like I'll need to re-base & refactor my code to match the work done there. Is there anything i can do to get this merged soon?

**Comment by yuxiang-zhang** [comment]
Hi @soggycactus, apologies for the delay, please rebase and refactor, then we'll go ahead with the review and merge, thanks 😄

**Comment by soggycactus** [comment]
@tim-finnigan @yuxiang-zhang I've closed this PR in favor of https://github.com/aws/aws-cli/pull/8163 - that PR has the latest changes & is developed against `develop` instead of `v2`

**Pull request closed without merging**
