### PR TITLE
Handle SIGPIPE

### PR DESCRIPTION
**Pull request by bcap**
*Issue #, if available:* 5899

*Description of changes:*

This commit changes the CLIDriver to consume potential SIGPIPE signals

In essence it will consume the signal and return a successful run.

This does changes process return code behaviour, as it will return a
zero code on broken pipes instead of previously returning a 120 code.
Because most of the pipelines only care about the return code of the
last process, and we can only receive a sigpipe if a next process in the
pipeline closes it, the return code from the aws cli in this case is not
really expressive

Before:

    % aws s3 ls | head -n 3 | cut -d ' ' -f 1
    2013-05-28
    2014-03-11
    2013-04-26

    [Errno 32] Broken pipe
    Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
    BrokenPipeError: [Errno 32] Broken pipe

After:

    python3 bin/aws s3 ls | head -n 3 | cut -d ' ' -f 1
    2013-05-28
    2014-03-11
    2013-04-26

(the `cut` in the pipeline is just to remove bucket names)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bcap** [comment]
This solves issue https://github.com/aws/aws-cli/issues/5899

**Comment by nhed** [comment]
why is this not being reviewed?

**Comment by ozturkberkay** [comment]
Are there any for merging this?

**Comment by bcap** [comment]
To be honest, and from the top of my head, I have no idea of what is necessary at this point for this to get merged. It's just overall lack of action or are we stuck at something else?

**Comment by pho3nixf1re** [comment]
I want to bump this. It is an annoying thing to workaround when crafting utilities no the shell.

**Comment by vandr0iy** [comment]
Please, someone merge this :sob: I'd like to follow my cloudformation templates in the CLI

**Comment by lorengordon** [comment]
I'd suggest giving the PR and the linked issue #5899 a 👍 reaction, as the awscli team is now monitoring those reactions and 10 are needed for them to move this forward...

* https://github.com/kdaily/aws-cli/blob/contrib-guide-proposal/proposals/contribution-guide.md#intake-stage-1

**Comment by bcap** [comment]
Yes! Unless I am missing something, apparently all I need is a code review to close this. Likely are base first as well due to its age

**Comment by stas00** [comment]
merge please?

**Comment by jsoref** [comment]
@kyleknap can you help?

**Pull request closed without merging**
