### PR TITLE
Remove make bucket from s3handler integration tests

### PR DESCRIPTION
**Pull request by JordonPhillips**
cc @kyleknap @jamesls

### CODE REVIEW

**Comment by jamesls** [comment]
Did you run this test?  This doesn't make any sense why we'd only remove make_bucket.  This won't actually work will it?

**Comment by JordonPhillips** [comment]
Updated

**Comment by JordonPhillips** [comment]
Updated

**Comment by kyleknap** [comment]
Looks good. :ship:

**Comment by jamesls** [comment]
:shipit:

**Pull request merged**
