### PR TITLE
issues/2948: use variable waiter_config

### PR DESCRIPTION
**Pull request by powersjcb**
helps to alleviate #2948

### CODE REVIEW

**Comment by oleyka** [comment]
Perhaps, `AWS_CF_WAIT_DELAY_*` would be better names for these envvars.

**Comment by sanathkr** [comment]
I like the feature, but not a big fan of env-vars spread out deep inside the files. Can we add a real parameter instead and pass it down? That way is easy to discover, well documented & tested.

**Comment by stealthycoin** [comment]
@powersjcb any interest in updating this PR per @sanathkr's feedback?

**Comment by JoeMcGuire** [comment]
+1 for this feature. While we wait for it I've requested an API rate increase.

**Pull request closed without merging**
