### PR TITLE
support AWS::Type::AppSync::FunctionConfiguration in artifact_exporter

### PR DESCRIPTION
**Pull request by xentek**
Adds support to artifact_exporter for the new CloudFormation type `AWS::Type::AppSync::FunctionConfiguration` (specifically the `RequestMappingTemplateS3Location` `ResponseMappingTemplateS3Location` properties).

There was already an existing PR (aws/aws-cli#3822) but it hasn't seen any activity for over 25 days. This PR improves upon the original by adding tests for not only the `AppSyncFunctionConfigurationRequestTemplateResource` and `AppSyncFunctionConfigurationResponseTemplateResource` classes, which were introduced in this pull but also tests for `AppSyncResolverRequestTemplateResource` and `AppSyncResolverResponseTemplateResource` that were introduced in a previous change.

fixes aws/aws-cli#3816

### CODE REVIEW

**Comment by xentek** [comment]
@jfuss @justnance this patch should be ready for review. cheers!

**Comment by xentek** [comment]
@jfuss @justnance sorry to be a pest, but any chance this could be reviewed and merged? thanks!

**Comment by jfuss** [comment]
@xentek I am not a maintainer of this repo and therefore have don't have control over commits.

**Comment by xentek** [comment]
@sanathkr @justnance Just updated this PR with the latest from aws/aws-cli@develop. Any chance we can merge this soon so I don't have to continue to maintain and use my fork in my own workflow?

Thanks!

**Comment by sharmmoh1983** [comment]
Is aws-package supports AppSync FunctionConfiguration?

**Comment by PatMyron** [comment]
> Is aws-package supports AppSync FunctionConfiguration?

[looks like this documentation needs to be updated if so:](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html)

https://github.com/aws/aws-cli/blob/286d13a5e1cc957d4ff8e50d7a04edf080ae9acd/awscli/examples/cloudformation/_package_description.rst#L11-L25

related: https://github.com/aws/aws-cli/pull/4029, https://github.com/aws-cloudformation/cfn-python-lint/issues/608, https://github.com/aws-cloudformation/cfn-python-lint/issues/1683

**Pull request merged**
