### PR TITLE
[Doc] Fix broken nested list in config-vars.rst

### PR DESCRIPTION
**Pull request by teppeis**
fix only format: http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles

### CODE REVIEW

**Comment by stealthycoin** [comment]
Hey @teppeis thanks for the submission. I just rebuilt the docs with your branch and it looks the same to me with your changes. Could you upload a screenshot of what it looks like once you get it working?

**Comment by teppeis** [comment]
@stealthycoin This `credential_source ` part

Before:
snapcrab_noname_2017-12-7_9-56-17_no-00

After:
snapcrab_noname_2017-12-7_9-55-11_no-00

These are previewed in GitHub.
I don't know your document build system, but [official ReST spec](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#bullet-lists)

> A sublist is a new list so requires a blank line above and below.

**Comment by stealthycoin** [comment]
Cool looks good to me.

**Comment by teppeis** [comment]
@stealthycoin thanks!

**Pull request merged**
