### PR TITLE
fix: allow colorama upgrade

### PR DESCRIPTION
**Pull request by greut**
*Description of changes:*

`awscli` can be installed using the latest  verison of `colorama`.

https://github.com/tartley/colorama/releases/tag/0.4.4

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kdaily** [comment]
Hi @greut, what's the use case for bumping the version of colorama? Thanks!

**Comment by kdaily** [comment]
Hi @greut, 

Can you please restrict the ceiling to `<=0.4.5` so that when this is released (in pre-release now) we can get that version?

We will double check the changes made up to that version. We also need to check our other builds to see if they need to be changed as well.

Thanks!

**Comment by greut** [comment]
> what's the use case for bumping the version of colorama? Thanks!

Other projects where **@dependabot** updates aggressively the version of literally everything.

Code-wise, the changes are very small.

https://github.com/tartley/colorama/compare/0.4.3...0.4.4#diff-c5e0a5afe307d2f07b5a39be35ee9cd6cd9fc68c1f4e7993d5efd3193b83e9ae

Note that your carefulness is greatly appreciated.

**Comment by mboboc** [comment]
When is this PR gonna be merged? The current version of colorama (<0.4.4) is conficting with djlint as well.
`colorama<0.5.0,>=0.4.4 (from djlint==0.7.1`)

**Comment by adriananeci** [comment]
Any updates on this PR? Many other requirements are failing because of this :(

**Comment by stealthycoin** [comment]
Merged in #6893

**Pull request closed without merging**
