### PR TITLE
Fixing broken aws-cli commands in examples/

### PR DESCRIPTION
**Pull request by vjeffz**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kdaily** [comment]
Hi @vjeffz,

Thanks for this contribution. There are some valid fixes here, but some changes are not correct. Just to call out a few:

- The example for `awscli/examples/codestar-connections/create-host.rst` is explicitly for a third party enterprise server.
- `awscli/examples/ec2/describe-byoip-cidrs.rst` does not need `max-results`.
- Some changes to parameter length (like` awscli/examples/ssm/register-task-with-maintenance-window.rst` don't change the length of the parameter, they were already the correct length).

Please verify that all of the changes are valid within their context. Feel free to open smaller targeted pull requests, as we'll be able to merge those in faster.

Thanks!

**Review by kdaily — CHANGES_REQUESTED** [review]
There are many great changes here, thanks! But there are too many that are not valid to pull this in all together. As it is, it will be difficult to pull this in due to the size. It would help if for some services (like `ec2`, among others) to pull out those into a separate PR to make it easier to review.

**Comment by vjeffz** [comment]
> * The example for `awscli/examples/codestar-connections/create-host.rst` is explicitly for a third party enterprise server.
> * `awscli/examples/ec2/describe-byoip-cidrs.rst` does not need `max-results`.
> * Some changes to parameter length (like` awscli/examples/ssm/register-task-with-maintenance-window.rst` don't change the length of the parameter, they were already the correct length).


Hi @kdaily,

Thanks. A bit of context , I'm creating a test harness for a piece of software I'm writing. It requires valid AWS commands to be run so I turned to the AWS CLI documentation to extract every AWS command for Linux, there's roughly ~5200 commands. You can see the full list here (https://gist.github.com/vjeffz/4a644973763574695b73d4b839a244e7). During this process a lot of them failed, the fixes to get them to run are what you see in this PR.

As a user, I would expect the examples provided by AWS should pass the syntax described in the synopsis of each command without producing the validation errors.

* `awscli/examples/codestar-connections/create-host.rst`  Correct. I'll revert this change.

* `awscli/examples/ec2/describe-byoip-cidrs.rst` . If I run the example provided it fails with:
```
$ aws ec2 describe-byoip-cidrs
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: --max-results
```

* ` awscli/examples/ssm/register-task-with-maintenance-window.rst`. While some are correct, there are some that are incorrect. For e.g:
```
aws ssm register-task-with-maintenance-window \
    --targets "Key=WindowTargetIds,Values=350d44e6-28cc-44e2-951f-4b2c9EXAMPLE" \
    --task-arn "AWS-RunShellScript" \
    --service-role-arn "arn:aws:iam::111222333444:role/MaintenanceWindowsRole" \
    --window-id "mw-ab12cd34eEXAMPLE" \
    --task-type "RUN_COMMAND" \
    --task-parameters  "{\"commands\":{\"Values\":[\"df\"]}}" \
    --max-concurrency 1 \
    --max-errors 1 \
    --priority 10

Parameter validation failed:
Invalid length for parameter WindowId, value: 19, valid min length: 20
```

Throughout this particular command the examples which use a window id of `"mw-ab12cd34eEXAMPLE"` are incorrect length. The working length with a window of id `"mw-ab12cd34ef56gh78"` is correct. I thought making them all the same would make it easier for a user  while making it clear they're example window ids so I used "`"mw-06cf17cbefEXAMPLE"` (Adding an extra `f` to the original example)

**Comment by kdaily** [comment]
Hi @vjeffz,

Thanks for your response! You've hit on at least one known issue (the CIDRS `max-results` should not be required) so glad to know that it's working!

> I'm creating a test harness for a piece of software I'm writing.

I'm really interested to know more about your approach here and if you could contribute it to the AWS CLI to run on our examples. The automated validation of examples is currently limited and it would be great to expand it:

https://github.com/aws/aws-cli/blob/develop/tests/functional/docs/test_examples.py

I think that starting with some easy cases to see how it works (e.g., multi-line commands should end with `\` not `/`, parameters with regular expression or length constraints should be enforced) would be overall more useful than a one-off change. Having a scoped set of things to check would help us reduce a bunch of false positives that need to be manually excluded somehow.

The big one that would need tweaking I see right now is how quoting is handled, but we can save that for another iteration.

Let me know what you think, and anything you've thought about the design for enabling/disabling specific validators.

**Comment by vjeffz** [comment]
Hi @kdaily 

The approach is a bit different to what you have in your example. We're building an inspection proxy ([kivera.io](kivera.io)) and the purpose of the test harness is to check our AWS engine is working correctly which uses http properties such as method, path, headers to work out the intended AWS action of the user. 

In our CI process we have a Github Actions workflow which uses the file I linked in the previous comment to generate [BATS](https://github.com/bats-core/bats-core) tests for each command in the examples folder. All 5200+ commands then run through the proxy (obviously we block all calls at the proxy so not to create a tonne of resources in AWS). While our test scenario is a bit more complex than what you require, it's also been able to validate if the command itself is correct.  An example test:

```
@test "AWS-EC2-620 Test proxy output matches Kivera.Error and contains action: UnassignPrivateIpAddresses " {
    result=$(aws ec2 unassign-private-ip-addresses --network-interface-id eni-e5aa89a3 --private-ip-addresses 10.0.0.82  --debug 2>&1 | grep "Kivera.Error" | grep "b'")
    action="UnassignPrivateIpAddresses"
    if ! [[ "${result,,}" =~ "${action,,}" ]]; then
        echo "# error: $result" >&3
        echo '# cmd: aws ec2 unassign-private-ip-addresses --network-interface-id eni-e5aa89a3 --private-ip-addresses 10.0.0.82 ' >&3
    fi
    [[ "${result,,}" =~ "${action,,}" ]]
}
```

I'm not sure how much help this is, we can explore integrating kivera (free license) into your ci process to run the tests or give you a demo on how it works if you feel it would be valuable. Alternatively, our approach could be tweaked to run through a regular squid proxy. Happy to contribute either way.

**Comment by RyanFitzSimmonsAK** [comment]
Hi @vjeffz, thanks for this pull request and for your patience.  This pull request is a little bit too broad in order to be merged.  I'm going to close it as not planned.  However, I do encourage you to open smaller, more targeted pull requests as mentioned earlier, because improving our examples is certainly something worth pursuing.

**Pull request closed without merging**
