### PR TITLE
Connect and read timeouts customization with providers

### LINKED ISSUE #5754: Make default: --cli-connect-timeout 6000
**Is your feature request related to a problem? Please describe.**
Problem: timeouts when using `aws lambda update-function-code` to upload zip file.
See the many problem reports: https://github.com/aws/aws-cli/issues/3842 and [StackOverflow](https://superuser.com/q/1604904/23334)

**Describe the solution you'd like**
Please make the option `--cli-connect-timeout 6000` be a default option

**Describe alternatives you've considered**
Require devs with this problem to search for the answer. (Current situation.)

**Additional context**
Making this change will not slow anything down, it simply solves the not uncommon case of slow networking and proxies.

### PR DESCRIPTION
**Pull request by gellanz**
*Issue #, if available:*

Fixes #5754.

*Description of changes:*
Implementation of the timeout customization from the CLI by creating a config chain with Providers. If the user type `--cli-connect-timeout` or `--cli-read-timeout` in the CLI it as has priority over the providers.
- With an env var I tried with the following: `export AWS_CONNECT_TIMEOUT=X` and `export AWS_READ_TIMEOUT=Y`
- For the config file I did the following: `aws configure set connect_timeout X` and `aws configure set read_timeout Y`
- The ConstantProvider is 60, as always. 
- The debug logs changed accordingly to my changes `MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (X, Y)`, I tried it by uploading a file to an S3 bucket

Also, I included a debug log to let the user know that a timeout was found within the providers (if he ever forgets it he can see the debug logs)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by stealthycoin** [comment]
Tests need to pass, and there need to be no conflicts before it can be reviewed.

**Comment by GustavoElizarraras** [comment]
Hi! Sorry for the late response. I have a doubt, the failed tests have nothing to do with the code I wrote, can you give me any advice to solve this?

**Comment by justindho** [comment]
Hi @GustavoElizarraras, if we take a look at the first test (`test_can_get_list_profiles_with_non_existent_profile_in_env_var`) that's failing, we can see that the [expected return code does not match the actual rc](https://github.com/aws/aws-cli/pull/6803/checks#step:6:621). Further looking into the internals of the [`run_cmd`](https://github.com/aws/aws-cli/blob/v2/awscli/testutils.py#L424) method, we can see that there is a [call](https://github.com/aws/aws-cli/blob/v2/awscli/testutils.py#L436) to the [`AWSCLIEntryPoint`](https://github.com/aws/aws-cli/blob/v2/awscli/clidriver.py#L157)'s main method. That seems like a good place to start putting some debugging statements (e.g., `import pytest; pytest.set_trace()`). Then, you can run `pytest tests/functional/test_args.py -k test_can_get_list_profiles_with_non_existent_profile_in_env_var` and step through the debugger to figure out where the issue might be.

**Comment by tim-finnigan** [comment]
Closing this PR as it hasn't been active for a couple years now. A new PR should incorporate the feedback above involving tests, and we can continue to track the feature request in https://github.com/aws/aws-cli/issues/5754.

**Pull request closed without merging**
