### PR TITLE
Added option to compare on ETag/MD5

### PR DESCRIPTION
**Pull request by adamsb6**
We have a use case for s3 sync in which we update a staging bucket with production data.  However, the current comparator options will fail to update keys in the staging bucket when they have been updated more recently than the production keys but do not differ in size.

This change adds a --compare-on-etag option that uses the ETag of the key or the md5 of the local file to determine whether or not the source and destination differ.

### CODE REVIEW

**Comment by rmharrison** [comment]
@kyleknap Curious about the status of this PR. Blocked because:
- It hasn't been rebased in a while (just needs to be brought-up to-date)?
- Doesn't support multipart-uploads (@adamsb6 comment about documentation insufficient) 
- Another blocking reason?

**Comment by simlu** [comment]
Would also really benefit from this. Same question as @rmharrison > What would be required to get this merged?

**Comment by phene** [comment]
How has this not been added yet?

**Comment by jdomingu** [comment]
+1. I would find this very helpful and also think that multipart uploads should not block this.

**Comment by acejam** [comment]
Bump

**Comment by acejam** [comment]
Any updates to this?

**Comment by bes1002t** [comment]
any progress?

**Comment by tim-finnigan** [comment]
Thanks for creating this PR and for your patience in waiting on a response. I recently brought this up for discussion as we are cleaning up the backlog. Now that S3 has extended [checksums](https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/), the CLI team is more inclined to explore using those for improvements to sync strategy rather than using Etags. Further investigation into this is still needed but unfortunately this PR cannot be considered at this time.

**Pull request closed without merging**
