### PR TITLE
Refactor Completer tests to use fake data

### PR DESCRIPTION
**Pull request by JordonPhillips**
In addition, I found and fixed a bug where used arguments were not being filtered if there was no service name or partial service name.

cc @jamesls @kyleknap

### CODE REVIEW

**Comment by kyleknap** [comment]
Tests look much better. I was debating if I would rather see the existing driver used with patches or the one of the fake cli drivers that we already have, but that would make the tests a lot more verbose because you would have to be supplying service JSON models and hooking into the event system to provide your own custom commands. The only downside with your approach is if we change the internals of the driver or any of the constructors for the command objects, the tests will fail. In the end, I think I like the approach you went with more. :ship:

**Comment by jamesls** [comment]
Much nicer.  Have you confirmed the code coverage numbers are the same/better than the previous tests?

**Comment by JordonPhillips** [comment]
@jamesls Code coverage is the same (I wrote these by converting each item into at least one assertion). Line coverage is down by one (we don't use the default clidriver in the tests).

**Comment by jamesls** [comment]
:shipit:  Perfect, thanks for checking.

**Pull request merged**
