### PR TITLE
Support cache for SharedCredentialFile

### PR DESCRIPTION
**Pull request by outcoldman**
Implementation to support cache for when MFA is used for shared credential files. See https://github.com/aws/aws-sdk/issues/529
Depends on https://github.com/boto/botocore/pull/1399

### CODE REVIEW

**Comment by ahl** [comment]
This would be extremely useful; I hope it gets merged.

**Comment by Kiddinglife** [comment]
need this

**Comment by wszzwpshh1** [comment]
Have to say that working with MFA in cli is rather unpleasant. You'll have to write some script to:
1. Get MFA device arn
2. Get session with MFA arn and MFA code
3. Store temp access key & token somewhere

It would be really nice if we can get a built-in solution e.g. a mfa_serial parameter in profile config etc.

**Comment by webbrandon** [comment]
Kinda wish someone would move or address this PR after 2 years of being open.  This would be useful and make it so we don't have get dev's setup with automation script to make development more productive.

**Comment by benjaminW78** [comment]
THIS MR would so well solve my problem. i want more security so i activated MFA but now it's becoming hell to use AWS CLI with mfa. but their is stuff that i can only do by AWS CLI for ECS ... so i'm stuck at trying to figure out how to have a seamless experience.

**Comment by whereismypen** [comment]
How can we (cloud users) be expected to improve our security stance when the cloud provider doesn't provide us with the tools. Please review and commit this.

**Comment by stealthycoin** [comment]
Updated the issue with guidance from our new contributing process #3172. Marking this PR as a DRAFT as we would not accept a PR that effects security and credential loading without a clear design doc that we can review and approve in advance. 
The issue itself is marked as blocked, which means it is waiting on a design spec to be written. Once someone posts a design and the design is iterated on with team member's and we approve it, it can be advanced to the contribution-ready stage.

**Comment by tim-finnigan** [comment]
Thank you for creating this PR and for your patience here. Regarding this point mentioned earlier:
>...we would not accept a PR that effects security and credential loading without a clear design doc that we can review and approve in advance.

This design doc will need to be considered at a cross-SDK level, and so we have transferred the corresponding issue (https://github.com/aws/aws-sdk/issues/529) to our cross-SDK repository for further tracking. Please 👍 the issue if also interested in this feature and comment there if you have any additional info to share.

**Pull request closed without merging**
