### PR TITLE
Adding the Dockerfile

### PR DESCRIPTION
**Pull request by marcieltorres**
*Issue #3553*

*Description of changes:*
So, I'm creating the Dockerfile to `aws-cli`, it's a simple Dockerfile but it's very helpful to CI/CD :).

For some tests, I'm pushing the image to my account in the docker hub: `https://hub.docker.com/r/marcieltorres/aws-cli`

Would be nice if the AWS push this image to the docker hub official account :)

*Special thanks [@shikow](https://github.com/shikow)

### CODE REVIEW

**Comment by jdel** [comment]
I absolutely support the very much needed idea of having an official docker image of the `awscli` which is justified only by the need to run `aws ecr get-login` to pull from any image from ECR.

I would love to see the `awscli-cwlogs` plugin installed so we can also pipe arbitrary scripts output to CW with the same container. It would be very nice to have this on minimal linux distributions that have no python / cloudwatch agent.

I install it in a custom image with:

```
[...TRUNCATED...]
 && pip install --no-cache-dir awscli awscli-cwlogs \
 && aws configure set plugins.cwlogs cwlogs
[...TRUNCATED...]
```

Provided the EC2 instance has the proper role, the following would stream pretty much any output to CW:

```
$ echo "whoop whoop" | docker run -i --rm aws/awscli:latest aws logs push --region eu-west-1 --log-group-name any-name --log-stream-name test-cwlogs
```

**Comment by jdel** [comment]
Also two ideas to make this a bit more future-proof: 
  - alpine:3.6 is currently [end of support on 01/05/2019](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases) it would be better to use 3.9
  - python2 as we all know will be gone next year and it would be wise to setup the docker image to use directly python3. 

The following `Dockerfile` works pretty well for me. Happy to make a PR on your repo if needed.

```Dockerfile
FROM alpine:3.9

COPY . /awscli

RUN apk --no-cache update && \
    apk --no-cache add python3 && \
    pip3 --no-cache-dir install -e /awscli/ awscli-cwlogs && \
    aws configure set plugins.cwlogs cwlogs && \
    rm -rf /var/cache/apk/*
```

**Comment by isaiahgrant** [comment]
Nice to see that there is already a PR out there!

Would you consider basing from [an official python image](https://hub.docker.com/_/python) like `python:3-alpine`?
This would save work during build time as we would no longer need to install python:
```
// We could potentially remove these lines.
apk --no-cache update && \
apk --no-cache add python py-pip py-setuptools && \
```

**Comment by kdaily** [comment]
We have implemented a Docker container image for the AWS CLI v2. We do not have plans to support a Docker container image for the v1 client.

**Pull request closed without merging**
