### PR TITLE
Support packaging with an inherited CodeUri from Globals

### PR DESCRIPTION
**Pull request by bmoller**
This supports #3376 describing what seems to be incorrect behavior.

The SAM specs state that `CodeUri` is a valid global for the `AWS::Serverless::Function` resource type. I would expect then that if I define `CodeUri` in my template's globals that the `aws cloudformation package` command would use that value and package my code using the global value.

This does not appear to be the current behavior. I added a check for globals just before iterating through a template's resources, and modified the `AWS::Serverless::Function` resource type to support missing `CodeUri` properties.

### CODE REVIEW

**Comment by bmoller** [comment]
Okay, looks like I'm going to need a test or two to maintain the test coverage

**Comment by 0xdevalias** [comment]
@bmoller any updates on this?

**Comment by hoegertn** [comment]
Any chance this will be supported soon?

**Comment by debora-ito** [comment]
Thanks for the PR! @sanathkr can you please review this?

**Comment by marcelomd** [comment]
Hi,
Any updates?
Thanks!

**Comment by wmonk** [comment]
Any chance this PR or the underlying bug could get looked at?

**Comment by justindho** [comment]
Apologies to everyone for the delayed response. The PR branch will need to be rebased onto the latest `develop` branch. We'll also want to add tests surrounding the proposed changes before the team takes a closer look at the PR.

As a side note, our team just put out a [contribution guide](https://github.com/aws/aws-cli/blob/v2/proposals/contribution-guide.md) detailing improvements to the contribution process. I'll be putting this PR in the "Implementation" stage of our [project board](https://github.com/orgs/aws/projects/21/views/2). Once a rebase is completed and tests are added, we can go ahead and mark this as "Ready for Review", where a maintainer will do a closer review.

**Comment by tim-finnigan** [comment]
Checking in — as mentioned in the [earlier comment](https://github.com/aws/aws-cli/pull/3391#issuecomment-1142621095), this PR would need to be rebased and have tests added before further review. I'm closing the PR as there hasn't been any further activity here in the last several months.

**Pull request closed without merging**
