### PR TITLE
Update uses dependencies for sphinx check

### PR DESCRIPTION
**Pull request by kdaily**
Update `actions/checkout` to v4 and `actions/setup-python` to v5 when building the GitHub pages-based contributing guide.

Builds are failing with the following:

```
> Run make html
  make html
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.15/x64/lib
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.5.0

Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
make: *** [Makefile:49: html] Error 2
Error: Process completed with exit code 2.

```

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kdaily** [comment]
That's not the right underlying issue, though we should update these. We pin the Sphinx version in the requirements file:

https://github.com/aws/aws-cli/blob/5b664476680449efded752c3b3a45c73f16f4fcd/requirements.txt#L1

```
Sphinx==4.5.0
```

**Review by nateprewitt — COMMENTED** [review]
Do we not have dependabot managing these? We should move to hashes ideally and let that all be automated.

**Comment by kdaily** [comment]
Agree, looking at enabling that for this branch. Testing locally first to see that Sphinx build is going to work OK with new versions.

**Comment by kdaily** [comment]
Added dependabot management of GH actions and dependencies on the `gh-pages` branch here:

https://github.com/aws/aws-cli/pull/9054

**Review by nateprewitt — APPROVED** [review]

**Pull request merged**
