### PR TITLE
IOWriterThread should continue even if a task fails

### PR DESCRIPTION
**Pull request by jamesls**
Otherwise this will cause a hang in the CLI because the
executor is waiting for the IO thread to process of all
its task items before exiting.

This actually fixes an integration test that would periodically
fail (the ctrl+c test).  I've also added an additional unit test
for this case.

This is actually how all the other threads (the task threads and the
result thread) work.  They catch exception and continue on to the
next task.

While this fixes the failing integration test, there are still additional
enhancements we can make.  We don't have a feedback mechanism
from within the IOthread to let other parts of the system know about
failed write tasks.  So while this technically "fixes" #1178 in the sense
that the code will no longer hang, it will still download all the content
from an S3 object.  We can improve this by failing fast as soon as we
have a streaming io task fail.  This will be a larger change and a
separate pull request.

cc @kyleknap @danielgtaylor

### CODE REVIEW

**Comment by kyleknap** [comment]
Looks good. :ship:

**Comment by kyleknap** [comment]
Wait. Can you remove the second sleep on the cntrl-c test as well if that is fixed when you merge?

**Comment by jamesls** [comment]
Do you mean this one (https://github.com/aws/aws-cli/blob/develop/tests/integration/customizations/s3/test_plugin.py#L335) or this one (https://github.com/aws/aws-cli/blob/develop/tests/integration/customizations/s3/test_plugin.py#L344).  The latter was needed to avoid excessive CPU on the system as well as it's basically a tight polling loop with no delay previously.

**Comment by kyleknap** [comment]
Yeah I was referring to the one that you just added. Given the reason, I am good with keeping it.

**Pull request merged**
