### PR TITLE
[v2] Remove ecr get-login command

### PR DESCRIPTION
**Pull request by kyleknap**
The command was deprecated in v1 and replaced with the `ecr get-login-password` command

### CODE REVIEW

**Comment by itajaja** [comment]
get-login was so useful :( where can I find the discussion with the reason for why it was removed?

**Comment by pda** [comment]
The deprecation PR is here: https://github.com/aws/aws-cli/pull/4877 but it doesn't have much more information. The addition of `get-login-password` happened in https://github.com/aws/aws-cli/pull/4874 after being proposed in https://github.com/aws/aws-cli/issues/4867 with a bit more context in https://github.com/aws/aws-cli/issues/3687#issue-374397564
/cc @itajaja

**Comment by rpnguyen** [comment]
Sorry that we did not make this more discoverable but we also put some information about the deprecation here: https://github.com/aws/containers-roadmap/issues/735

**Comment by rpnguyen** [comment]
We also put some information about the deprecation here: https://github.com/aws/containers-roadmap/issues/735

**Comment by itajaja** [comment]
alas, I guess it's too late now, but while `get-login` is surely more flexible, the old command was much easier to use, and I wish we could have have both. having to specify the aws account id is surely cumbersome.

**Comment by rpnguyen** [comment]
You may also consider using the [ECR Docker credential helper](https://github.com/awslabs/amazon-ecr-credential-helper) which removes the need to call an authentication CLI command altogether.

**Pull request merged**
