### PR TITLE
Replace the six,PY3: is ture

### PR DESCRIPTION
**Pull request by Sergius-Nyah**
The if six.PY3: condition could be replaced with if True: since Python 2 is no longer supported.

 This change simplifies the code and removes the dependency on the six library.

### CODE REVIEW

**Comment by a-detiste** [comment]
please

**Comment by Sergius-Nyah** [comment]
> please

I don't get please.

**Comment by a-detiste** [comment]
please merge / proceed / go forward with removal of six everywhere

**Comment by Sergius-Nyah** [comment]
> > please
> 
> I don't get please.

So how do I do that ? It's solely in your place to approve and merge.

**Comment by a-detiste** [comment]
I don't own this project

**Comment by Sergius-Nyah** [comment]
> I don't own this project

Okay sir. 
But please, what do you suggest  ?

**Comment by kellertk** [comment]
@Sergius-Nyah as we've mentioned before, creating a large number of PRs against this repository is not the way to get your changes in. If you are still interested in contributing, please consolidate all of your PRs into one PR so we can review, and review our contributing guide.

**Pull request closed without merging**
