### PR TITLE
cloudformation deploy: Use template parameter default value only on stack creation

### LINKED ISSUE #2460: aws cloudformation deploy not maintain stack parameters
With latest version of awscli, cloudformation deploy not maintain stack parameters.
aws cloudformation deploy get template defaults instead of stack parameters.

With aws-cli/1.11.19 and botocore/1.4.83 are working correctly.

### PR DESCRIPTION
**Pull request by sanathkr**
Fixes #2460 

There are four state combinations:
    YES Override + YES Stack: Use overriden value
    YES Override + NO Stack: Use overriden value
    
    NO Override + YES Stack: Set UsePreviousValue to True
      ^^ This commit fixes this case. Earlier we were letting CloudFormation pickup default value from template
    
    NO Override + NO Stack: Skip parameter to force CloudFormation to use template default value. UsePreviousValue=True will fail here because stack does not have any previous state.

### CODE REVIEW

**Comment by sanathkr** [comment]
Build is failing for python2.6 on an unrelated test: `tests.functional.rds.test_generate_db_auth_token.TestGenerateDBAuthToken)`. Not sure what is happening. Can someone help?

**Comment by kyleknap** [comment]
@sanathkr could you rebase off of develop? We fixed the test in this PR: https://github.com/aws/aws-cli/pull/2569 which is now merged.

**Comment by dstufft** [comment]
It looks like this didn't get rebased cleanly?

**Comment by stealthycoin** [comment]
Yea its got all the rds customizations in there.

**Comment by sanathkr** [comment]
Rebased again and pushed in a new branch at #2573

**Pull request closed without merging**
