### PR TITLE
Replace outdated bucket placeholders with updated example buckets.

### PR DESCRIPTION
**Pull request by DavidSouther**
*Issue #, if available:*

There is an internal effort to rename placeholder BUCKET_NAMES with reserved bucket_names across AWS docs.

*Description of changes:*

Performed an update across example files using `sed -I '' -f .../buckets.sed **/*.rst` from the examples folder.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by DavidSouther** [comment]
Script was 

```
s/DOC-EXAMPLE-BUCKET/amzn-s3-demo-bucket/g
s/DOC-EXAMPLE-BUCKET1/amzn-s3-demo-bucket1/g
s/DOC-EXAMPLE-BUCKET2/amzn-s3-demo-bucket2/g
s/DOC-EXAMPLE-BUCKET3/amzn-s3-demo-bucket3/g
s/DOC-EXAMPLE-SOURCE-BUCKET/amzn-s3-demo-source-bucket/g
s/DOC-EXAMPLE-DESTINATION-BUCKET/amzn-s3-demo-destination-bucket/g
s/DOC-EXAMPLE-SOURCE-BUCKET1/amzn-s3-demo-source-bucket1/g
s/DOC-EXAMPLE-DESTINATION-BUCKET1/amzn-s3-demo-destination-bucket1/g
s/DOC-EXAMPLE-SOURCE-BUCKET2/amzn-s3-demo-source-bucket2/g
s/DOC-EXAMPLE-DESTINATION-BUCKET2/amzn-s3-demo-destination-bucket2/g
s/DOC-EXAMPLE-LOGGING-BUCKET/amzn-s3-demo-logging-bucket/g
s/DOC-EXAMPLE-LOGGING-BUCKET1/amzn-s3-demo-logging-bucket1/g
s/DOC-EXAMPLE-LOGGING-BUCKET2/amzn-s3-demo-logging-bucket2/g
s/DOC-EXAMPLE-WEBSITE-BUCKET/amzn-s3-demo-website-bucket/g
s/DOC-EXAMPLE-WEBSITE-BUCKET1/amzn-s3-demo-website-bucket1/g
s/DOC-EXAMPLE-WEBSITE-BUCKET2/amzn-s3-demo-website-bucket2/g
s/DOC-EXAMPLE-BUCKET--usw2-az1--x-s3/amzn-s3-demo-bucket--usw2-az1--x-s3/g
s/DOC-EXAMPLE-BUCKET1--usw2-az1--x-s3/amzn-s3-demo-bucket1--usw2-az1--x-s3/g
s/DOC-EXAMPLE-BUCKET2--usw2-az1--x-s3/amzn-s3-demo-bucket2--usw2-az1--x-s3/g
s/DOC-EXAMPLE-BUCKET3--usw2-az1--x-s3/amzn-s3-demo-bucket3--usw2-az1--x-s3/g
s/DOC-EXAMPLE-SOURCE-BUCKET--usw2-az1--x-s3/amzn-s3-demo-source-bucket--usw2-az1--x-s3/g
s/DOC-EXAMPLE-DESTINATION-BUCKET--usw2-az1--x-s3/amzn-s3-demo-destination-bucket--usw2-az1--x-s3/g
s/DOC-EXAMPLE-SOURCE-BUCKET1--usw2-az1--x-s3/amzn-s3-demo-source-bucket1--usw2-az1--x-s3/g
s/DOC-EXAMPLE-DESTINATION-BUCKET1--usw2-az1--x-s3/amzn-s3-demo-destination-bucket1--usw2-az1--x-s3/g
s/DOC-EXAMPLE-SOURCE-BUCKET2--usw2-az1--x-s3/amzn-s3-demo-source-bucket2--usw2-az1--x-s3/g
s/DOC-EXAMPLE-DESTINATION-BUCKET2--usw2-az1--x-s3/amzn-s3-demo-destination-bucket2--usw2-az1--x-s3/g
```

**Comment by elysahall** [comment]
Commenting for posterity. Spoke to David offline about fixing some of the regex replacements.

**Comment by DavidSouther** [comment]
Looks like a couple stragglers:

```
s/awsamzn-s3-demo-bucket/amzn-s3-demo-bucket/gi
s/MY-S3-amzn-s3-demo-bucket/amzn-s3-demo-bucket/gi
```

**Review by elysahall — APPROVED** [review]
LGTM

**Review by kdaily — APPROVED** [review]

**Pull request merged**
