### PR TITLE
Add support for aws cloudformation package of AWS::AppSync::FunctionC…

### PR DESCRIPTION
**Pull request by mkrn**
Add support for aws cloudformation package of AWS::AppSync::FunctionConfiguration RequestMappingTemplateS3Location and ResponseMappingTemplateS3Location properties

Related issue https://github.com/aws/aws-cli/issues/3816

### CODE REVIEW

**Comment by Zerquix18** [comment]
+1 Templates look really messy without this

**Comment by xentek** [comment]
Is this ready for merge? /cc: @justnance

**Comment by xentek** [comment]
I forked from aws/aws-cli@develop and applied the @mkrn's patch 

I can confirm it works and am now installing the patched CLI with: 

`pip install --user --upgrade -e git+https://github.com/groundbreaker/aws-cli.git@develop#egg=awscli` 

As of this writing the aws-cli version is `v1.16.90`. 

_I can't promise I will keep the fork up to date, so I recommend you doing your own fork, etc_

**Comment by jfuss** [comment]
@mkrn Make sure you update the tests to include coverage of the new resources: https://github.com/aws/aws-cli/blob/develop/tests/unit/customizations/cloudformation/test_artifact_exporter.py#L62

**Comment by xentek** [comment]
HI @jfuss! I submitted a new PR to replace this one, since I wasn't sure if @mkrn was going to get back to this PR (and I'd really like to go back to using the official release with my team 😎). 

Perhaps we can merge #3833 and can close out this one? 

Cheers!

:shipit:

**Comment by sharmmoh1983** [comment]
Is the support added? Can I use aws package command for FunctionConfiguration?

**Comment by xentek** [comment]
@sharmmoh1983 yes, `aws-cli/1.16.111` has the support for `FunctionConfiguration`

**Comment by sharmmoh1983** [comment]
@xentek Thanks for your input. I am failing to install aws-cli/1.16.111 . Currently I am using aws-cli/1.16.99

Is there any straightforward way to upgrade on Mac? Usual commands are not working?

**Comment by xentek** [comment]
@sharmmoh1983 `pip install --upgrade awscli` worked for me. If you used homebrew to originally install the cli, homebrew's formula always runs behind the official release (`brew info awscli` reports version `1.16.100` on my machine).  

If that is the case, then this might do the trick for you: `brew uninstall awscli && pip install awscli`.

**Comment by sharmmoh1983** [comment]
@xentek I ran the mentioned commands and version in my system is aws-cli/1.16.114 which is higher than 1.16.111 but still  `FunctionConfiguration ` is not working as its happening for other resources for  aws package command

I have also mentioned the snapshot of cloudformation script generated after aws package command in above comments?

Do I have to have only 1.16.111 version to make it work ?

**Comment by xentek** [comment]
@sharmmoh1983 `aws --version` will tell you the version you have installed. `which aws` will tell you where that aws version is coming from. Due to numerous factors (homebrew vs pip, python virtualenvs, user vs system installs (e.g. `pip install --user`), you could end up with multiple (conflicting) versions of a python module installed. It will be hard for me to debug that from here.

`1.16.111` is the version my fix showed up in, and is the version I'm still running (and using every day to package my AppSync `FunctionConfiguration`). I can't imagine that my patch was removed from later versions, so `1.16.114` should still be fine.

I'm afraid I have no other advice to provide to get the latest version installed on your machine. Happy Hunting!

**Comment by sharmmoh1983** [comment]
@xentek Thanks for your inputs. It is working now on version 1.16.114

**Review by justindho — APPROVED** [review]
Thanks, @mkrn!

**Pull request merged**
