### PR TITLE
rectified set-endpoint-attributes.rst [get->set]

### LINKED ISSUE #5446: Typo in SNS docs
Hi, thanks for your work :octocat: 

I found a typo in the SNS set-endpoint-attributes example (both in v1 and v2)
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sns/set-endpoint-attributes.html#examples
(get -> set)

> The following **set**-endpoint-attributes example disables the specified platform application endpoint.
aws sns **get**-endpoint-attributes \
snip...

### PR DESCRIPTION
**Pull request by nitish-awasthi**
Fixed #5446

*Issue #5446 :*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nitish-awasthi** [comment]
PR!

**Review by kdaily — APPROVED** [review]
Thanks @nitish-awasthi!

**Comment by kdaily** [comment]
Hi @nitish-awasthi - after review I noticed that there was errant documentation in the `get-endpoint-attributes` command as well. It looks like a copy/paste between the get and set commands. I pushed a change here. Let me know that it looks OK and I'll re-review with the team. Thanks again!

**Comment by stobrien89** [comment]
@nitish-awasthi,

Hope you don't mind— I rebased to get this ready to merge.

**Review by justindho — APPROVED** [review]
Thanks, @nitish-awasthi!

**Pull request merged**
