### PR TITLE
Add example for creating buckets not in us-east-1

### PR DESCRIPTION
**Pull request by kyleknap**
Fixes https://github.com/aws/aws-cli/issues/1667

cc @jamesls @mtdowling @rayluo @JordonPhillips

### CODE REVIEW

**Comment by rayluo** [comment]
:ship:

**Comment by jamesls** [comment]
:shipit:

**Comment by timkendrick** [comment]
Original reporter here - FYI this doesn't actually fix the issue I was talking about.

The misleading `--region` argument in the `create-bucket` example is [still there](https://github.com/kyleknap/aws-cli/blame/45c283ef3177ea9256c1d4bfab2b0f52a008a54b/awscli/examples/s3api/create-bucket.rst#L3)...

**Comment by kyleknap** [comment]
It is unrelated to ``create-bucket``. It just specifies with what endpoint the request will be sent. S3 is a little special because even if you specify ``eu-west-1`` as the region, we will send it to the main s3 endpoint ``s3.amazonaws.com`` because it will reroute the request to the appropriate endpoint.

For the common use case, ``--region`` is not required to be the same as the region you are trying to create the bucket. However, it **is** required for some edge cases like in signature version 4 only regions like ``eu-central-1`` or if you are straight up using signature version 4 because signature version 4 requires the correct region to be specified and we will no longer be using the ``s3.amazonaws.com`` endpoint. So the example will break if I remove that ``--region`` argument for signature version 4 cases.

**Comment by timkendrick** [comment]
Thanks for the explanation @kyleknap, that makes a lot of sense. Sorry for the confusion.

**Comment by kyleknap** [comment]
No problem. Glad to help!

**Pull request merged**
