### PR TITLE
Remove deprecated -e option for docker login

### PR DESCRIPTION
**Pull request by zackhsi**
```
Warning: '-e' is deprecated, it will be removed soon. See usage.
```

### CODE REVIEW

**Comment by jamesls** [comment]
Associated issue: #1926 

I just commented on that issue (https://github.com/aws/aws-cli/issues/1926#issuecomment-221278732), but it looks like there's issues regarding backwards compatibility of remove the `-e` option.

I'm following up with the ECR team, but for now I think we'll have to keep this unless there's a way to preserve backwards compatibility.

**Comment by sentientmonkey** [comment]
We've filed an issue with docker and you can track it here: [#23390](https://github.com/docker/docker/issues/23390)

We will update this issue based on the outcome.

**Comment by cauealves** [comment]
👍

**Comment by neurolabs** [comment]
The -e flag is removed in docker 17.06, so aws ecr get-login is effectively broken.

Please merge this pull request.

**Comment by alasdairnicol** [comment]
@neurolabs you can use the `--no-include-email` option introduced in #2619

**Comment by alasdairnicol** [comment]
@jamesls I believe this should have been closed by #2619 along with #1926.

**Comment by neurolabs** [comment]
works with `--no-include-email`, could be closed. Although I didn't find this option and resorted to `|sed 's/-e none//'` first. More documentation would probably be a good thing.

**Comment by neurolabs** [comment]
Or maybe switch the default to `--no-include-email`? I would imagine that that would break stuff for less people than the other way around.

**Comment by almorelle** [comment]
Any update on this ?

**Comment by cauealvesbraz** [comment]
Hey @almorelle, 

After I updated my `aws-cli` the problems are solved.

I'm using this stack:
```bash
aws-cli/1.16.110 Python/3.7.2 Darwin/18.2.0 botocore/1.12.100
```

**Comment by almorelle** [comment]
@cauealvesbraz I'm at aws-cli/1.16.90 Python/3.7.2 Darwin/18.2.0 botocore/1.12.80 which doesn't seem far behind but I'll try to upgrade anyway. thanks

**Pull request closed without merging**
