### PR TITLE
Make builds fail if pr to master is made

### PR DESCRIPTION
**Pull request by kyleknap**
I think this is working: https://github.com/aws/aws-cli/pull/1755 and erroring out with this sample build: https://travis-ci.org/aws/aws-cli/jobs/105521867

Here are environment variable references that Travis uses: https://docs.travis-ci.com/user/environment-variables/

cc @jamesls @mtdowling @rayluo @JordonPhillips

### CODE REVIEW

**Comment by kyleknap** [comment]
Hold on the review. I need to fix my script.

**Comment by jamesls** [comment]
:shipit:

**Comment by kyleknap** [comment]
I am going to close this pull request. Travis is running only this pr with respect to develop. I want to see the one to master to fail

**Comment by kyleknap** [comment]
Alright here is the successful failed build to master: https://travis-ci.org/aws/aws-cli/jobs/105531057. And now it passes for develop. Merging.

**Pull request merged**
