### PR TITLE
Improve incorrect access policy in s3api example

### PR DESCRIPTION
**Pull request by bdavs3**
*Description of changes:* Fix the "Resource" key in an SNS Access Policy so that it correctly reflects an SNS topic ARN, not an S3 bucket.

To confirm that this is correct, see the relevant [AWS docs](https://docs.aws.amazon.com/sns/latest/dg/sns-access-policy-use-cases.html#sns-grant-aws-account-access-to-topic).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kdaily** [comment]
Thanks @bdavs3!

In this case, wouldn't the SNS topic need to be the same as in the example command (`arn:aws:sns:us-west-2:123456789012:s3-notification-topic`)?

**Review by kdaily — CHANGES_REQUESTED** [review]
Thanks @bdavs3!

In this case, wouldn't the SNS topic need to be the same as in the example command (`arn:aws:sns:us-west-2:123456789012:s3-notification-topic`)?

**Comment by bdavs3** [comment]
@kdaily Yep, I agree. I amended my change.

**Comment by justindho** [comment]
Hi @bdavs3, thanks for pointing out this issue initially. It looks like this was fixed in #6866, which was merged a few weeks ago. As a result, I will be closing this PR.

**Pull request closed without merging**
