### PR TITLE
Add ignoreexisting to syncstrategy so files with the same name not sync'd

### PR DESCRIPTION
**Pull request by awuceres**
We would like a strategy so that once the files are sync'd once, it will not clobber local files as we modify them.

This strategy allows us to only transfer files that do not exist.

I might also be missing some places where I need to change the files.

### CODE REVIEW

**Comment by awuceres** [comment]
I have renamed transferonce to ignoreexisting to be more similar to rsync.

**Comment by awuceres** [comment]
Comments please?  Is it something I'm missing?  Thanks.

**Comment by awuceres** [comment]
Sorry to bother, but any comments?  
Is the code I wrote really bad, or I'm missing something, or you haven't gotten around to review yet, or you don't think this is a good feature, or should I file an issue to discuss this?
Much appreciated.

**Comment by tim-finnigan** [comment]
Hi @awuceres, apologies that it has taken so long to get a response on this PR. I think it fell off the team's radar because it was not linked to a corresponding issue. I found a couple issues that look related:
* https://github.com/aws/aws-cli/issues/1449
* https://github.com/aws/aws-cli/issues/404
* https://github.com/aws/aws-cli/issues/2874

Although that last issue references `cp/mv`, the `sync` command is also mentioned several times throughout the issue (for example [here](https://github.com/aws/aws-cli/issues/2874#issuecomment-361306387)). You could try using the `--size-only` parameter as [suggested here](https://github.com/aws/aws-cli/issues/2874#issuecomment-710097606) as that might address your use case. 

All that being said, we want to consolidate related issues to help with tracking going forward. Please let us know if one of those existing issues or a new issue is the best place to track this feature request. This PR can be revisited in the future once we have a corresponding issue and more discussion regarding the use case and request.

**Pull request closed without merging**
