### PR TITLE
Add support for AWS::Synthetics::Canary.Code to aws cloudformation package

### PR DESCRIPTION
**Pull request by stilvoid**
*Issue #, if available:* https://github.com/aws/aws-cli/issues/5230

*Description of changes:*

Adds support to `aws cloudformation package` for `AWS::Synthetics::Canary` by introducing a new class `ResourceWithS3UrlProperties` that performs mostly the same function as `ResourceWithS3UrlDict` but has the additional feature that it preserves existing properties.

This is required because, unlike `AWS::Lambda::Function`, the Canary resource defines the `Handler` and S3 location properties within the same dict.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Example input:

```yaml
MyCanary:                                                                                                                                               
  Type: "AWS::Synthetics::Canary"                                                                                                                       
  Properties:                                                                                                                                           
    ArtifactS3Location: s3://abucket/                                                                                                           
    Code:                                                                                                                                               
      Handler: foo.handler                                                                                                                              
      Script: foo.py                                                                                                                                    
    ExecutionRoleArn: !GetAtt MyRole.Arn                                                                                                                
    Name: CanaryName                                                                                                                               
    RuntimeVersion: syn-1.0                                                                                                                             
    Schedule:                                                                                                                                           
      Expression: rate(1 minute)                                                                                                                        
    StartCanaryAfterCreation: false
```

Example output:

```yaml
MyCanary:                                                                                                                                               
  Type: "AWS::Synthetics::Canary"                                                                                                                       
  Properties:                                                                                                                                           
    ArtifactS3Location: s3://abucket/                                                                                                           
    Code:                                                                                                                                               
      Handler: foo.handler           # Note that the Handler property has been preserved                                                                                                                    
      S3Bucket: anotherbucket
      S3Key: 0123456789abcdef                                                                                                                           
    ExecutionRoleArn: !GetAtt MyRole.Arn                                                                                                                
    Name: CanaryName                                                                                                                               
    RuntimeVersion: syn-1.0                                                                                                                             
    Schedule:                                                                                                                                           
      Expression: rate(1 minute)                                                                                                                        
    StartCanaryAfterCreation: false
```

### CODE REVIEW

**Comment by stilvoid** [comment]
Obviously the coverage has decreased as I've added a whole new class but given that there is no framework for testing the existing features of `package`, I don't think it's reasonable for me to add those in the scope of this PR. Let me know if I've missed something.

**Comment by stilvoid** [comment]
This commit applies cleanly to `v2` also. Is there a separate process for pull requests into `v2` or those handled by the AWS CLI team rebasing occasionally?

**Comment by kdaily** [comment]
Hi @stilvoid, I will notify the owner of the CloudFormation packaging customization about this PR.

**Comment by aBurmeseDev** [comment]
Hi @stilvoid - thanks for this PR and for your patience on hearing back. Upon team discussion, we decided that further internal discussions are needed with other SDK teams to keep consistency between SDKs. With that said, we might consider implementing this in the cross-SDK approach in the future and close this for now.

**Pull request closed without merging**
