### PR TITLE
Fix #1454 by optimizing number of S3 calls by using the prefix API parameter

### LINKED ISSUE #1454: aws s3 cp doesn't work with prefix
From a bucket containing millions of files, I want do download a few thousand based on their prefix. 

Note: using --exclude "*" --include "myprefix" works, but is impractical since it lists all the files and applies the filter afterwards.

The problem is aws s3 cp adds a trailing "/" after the prefix I specify. In the example below you can see that logs/2015-08-17 becomes logs/2015-08-17/ 
This additional "/" leads to an empty result set, since the keys in the bucket have the form logs/YYYY-MM-DD-HH-MM-SS-RANDOM).

> aws s3 cp s3://mybucket/logs/2015-08-17 . --recursive --dryrun --debug

2015-08-17 21:48:32,026 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.27 Python/2.7.6 Linux/3.14.13-c9, botocore version: 0.108.0
2015-08-17 21:48:32,026 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'cp', 's3://mybucket/logs/2015-08-17', '.', '--recursive', '--dryrun', '--debug']
....
2015-08-17 21:48:32,088 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7ff9d3ec3e50> (verify_ssl=True) with params: {'query_string': {u'prefix': u'logs/2015-08-17/', u'encoding-type': 'url'}, 'headers': {}, 'url_path': u'/mybucket', 'body': '', 'method': u'GET'}

### PR DESCRIPTION
**Pull request by ralph-tice**
Issue #, if available:
#1454

This fix has the nice benefit of constructing filters once, but the downside of being horribly specific.

### CODE REVIEW

**Comment by ralph-tice** [comment]
Rebased on develop.

**Comment by ralph-tice** [comment]
@justindho do you need me to rebase or anything?

**Comment by aBurmeseDev** [comment]
HI @ralph-tice - thanks for creating this PR and apology for the delay. 

After reviewing this with the developer team, we'd need to discuss more on finding comprehensive approach rather than just addressing edge cases. If you're still interested, please rebase it against the latest branch for further discussion with the team going forward.

**Comment by ralph-tice** [comment]
Rebase went fine, just like in 2017 ;)

**Comment by ralph-tice** [comment]
Not sure what the dev team's thoughts are, but after sitting with this issue more and surveying the rest of the code, and given the low rate of change of this section of code over the last six years, I think it's fine to merge as-is.  There's similarly specific fixes just a few lines below the meat of this change for deleting manually created "folders" while otherwise ignoring them for non-delete operations.

**Comment by tim-finnigan** [comment]
Checking in — thank you @ralph-tice for creating this PR and rebasing. Upon further discussion with the team, their stance is still that a more comprehensive approach is needed here as @aBurmeseDev mentioned. There are several S3 issues currently open involving s3 cp/sync and filtering, and more review is needed in order to come up with a more holistic plan for addressing these issues. 

We may revisit the changes proposed here in the future and will continue tracking the issue in https://github.com/aws/aws-cli/issues/1454, but at this time the team decided that this PR should be closed. Thanks again for your contributions and patience here, we understand the frustrations around issues being open for long periods of time and we are trying to get better at addressing these.

**Pull request closed without merging**
