### PR TITLE
Adds example for dynamodb put-item conditional expression 

### PR DESCRIPTION
**Pull request by bchav**
Just a quick example for conditional expressions to help with syntactical questions.

### CODE REVIEW

**Comment by kyleknap** [comment]
Thanks! The content looks good to me.

I think the ReStructuredText formatting looks a little off when I look at your [branch](https://github.com/bchav/aws-cli/blob/develop/awscli/examples/dynamodb/put-item.rst) as everything that you added looks to be in a code block.

I think you should fix that by making sure that are two newlines after every the end of every codeblock (the ``::`` notation). Also, could you move the line ``If the key already exists, you should see:`` out of the ``Output`` code block? The output codeblock should be reserved to the error being thrown.

**Comment by bchav** [comment]
Thanks, that took a bunch of trial and error to get formatting correct here :+1:

**Comment by kyleknap** [comment]
Awesome. Looks much better. One last thing. Could you squash your commits into a single commit and repush the branch? There are a lot of "formatting" commits that not ideal to have in the commit history.

**Comment by bchav** [comment]
Squashed. Let me know if everything checks out.

**Comment by kyleknap** [comment]
Thanks! Merging.

**Pull request merged**
