### PR TITLE
addresses #3726 - propagate use_json to cf template artifacts

### PR DESCRIPTION
**Pull request by tjstansell**
issue #3726 
This propagates the --use-json option when running `aws cloudformation package` to apply to the referenced cloudformation templates it publishes to s3.

### CODE REVIEW

**Comment by stealthycoin** [comment]
@tjstansell Thanks for the submission, could you take a look at getting the tests passing so we can merge this? If you don't have time one of us can take this PR.

**Comment by tjstansell** [comment]
yeah... let me update the PR and fix the test.

**Comment by tjstansell** [comment]
Yay.  Finally got all the tests passing.

**Comment by tjstansell** [comment]
Haha. 4+ years later isn't patience. I moved on long ago. Feel free to take this and update it yourselves or just close this.

**Pull request closed without merging**
