### PR TITLE
Improve error message for streaming

### PR DESCRIPTION
**Pull request by kyleknap**
Raise an error if the user tries to use --recursive

Fixes https://github.com/aws/aws-cli/issues/1771

cc @jamesls @JordonPhillips

### CODE REVIEW

**Comment by jamesls** [comment]
:shipit:

**Comment by davidwarshaw** [comment]
Are the docs in the repo? It would be great if they were updated as well.

**Comment by kyleknap** [comment]
Depends, what part of the docs were you looking to get updated?

**Comment by davidwarshaw** [comment]
I suggest a note in the entry for "Downloading a S3 object as a local file stream", indicating the recursive flag is not valid in combo:
http://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

**Comment by davidwarshaw** [comment]
While we're being thorough, it should be "Downloading **an** S3 object as a local file stream". :)

**Comment by davidwarshaw** [comment]
PR for doc update here: aws/aws-cli/pull/1840

**Pull request merged**
