### PR TITLE
Amazon Omics command examples

### PR DESCRIPTION
**Pull request by mwunderl**
*Issue #, if available:* N/A

*Description of changes:*
Add examples for Amazon Omics commands.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mwunderl** [comment]
@hssyoo can you help review these examples?

**Comment by mwunderl** [comment]
@kdaily Can you take a look?

**Comment by elysahall** [comment]
LGTM

**Review by kdaily — APPROVED** [review]
Thanks! 🚢

**Review by elysahall — APPROVED** [review]

**Comment by mwunderl** [comment]
Thank you both 🦅

**Pull request merged**
