### PR TITLE
Support ruamel-yaml >= 0.17.22

### PR DESCRIPTION
**Pull request by yan12125**
*Issue #, if available:*

N/A

*Description of changes:*

Some aws-cli changes are needed for ruamel-yaml 0.17.22 and 0.17.29. See individual commit messages.

This PR supersedes https://github.com/aws/aws-cli/pull/8257

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by doxie-king** [comment]
any update on this PR? https://github.com/aws/aws-cli/issues/5943#issuecomment-1683325140

**Comment by yan12125** [comment]
Sorry, I didn't notice I was testing against some older version instead of the proposed upper bound 0.17.32. I pushed one more change needed for that version. A similar change was also proposed in https://github.com/aws/aws-cli/pull/7967. That pull request was closed with "This is fixed in a later version of the library", but that is not exactly the case as I described in a newer upstream ticket https://sourceforge.net/p/ruamel-yaml/tickets/482/.

**Comment by yan12125** [comment]
> Sorry, I didn't notice I was testing against some older version instead of the proposed upper bound 0.17.32. I pushed one more change needed for that version. A similar change was also proposed in #7967. That pull request was closed with "This is fixed in a later version of the library", but that is not exactly the case as I described in a newer upstream ticket https://sourceforge.net/p/ruamel-yaml/tickets/482/.

The issue is actually fixed with ruamel-yaml 0.17.36, so I dropped the workaround and raised the lower bound for this dependency.

**Comment by yan12125** [comment]
This pull request was part of efforts on keeping compatibility between aws-cli v2 and newer Python dependencies on Arch Linux. Now that I gave up maintaining aws-cli-v2 in Arch Linux repos (https://github.com/aws/aws-cli/issues/8342#issuecomment-2068024974), the efforts are abandoned.

**Pull request closed without merging**
