### PR TITLE
updating README v2 with instructions for Arm

### PR DESCRIPTION
**Pull request by AGSaidi**
*Issue #, if available:*

*Description of changes:*
updating README v2 with instructions for Arm

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by kdaily — COMMENTED** [review]
Hi @AGSaidi, thanks for the PR. I'm going to hold off pulling this in until I finish a re-write of the V2 README (https://github.com/aws/aws-cli/pull/5423).

**Review by nitish-awasthi — APPROVED** [review]

**Comment by justindho** [comment]
I'm going to label this PR as blocked until #5423 is resolved.

**Comment by tim-finnigan** [comment]
This update looks good to me and consistent with the User Guide: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html. Since https://github.com/aws/aws-cli/pull/5423 was closed I think this can be merged in an upcoming release.

**Review by kdaily — APPROVED** [review]
Thanks! 🚀

**Pull request merged**
