### PR TITLE
Adding new examples for Textract service

### PR DESCRIPTION
**Pull request by bisdavid**
*Issue #, if available:*

*Description of changes:*
Added new examples for the Textract service.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bisdavid** [comment]
I've fixed the files by removing all the \r and replacing with \n.

Please advise if these fixes are adequate.  Thanks!

**Comment by dstufft** [comment]
For some reason the formatting is looking wonky. I think you might want to put the ``::`` on it's own line in each case. If you look at the rendered diff in GitHub you can see it's not rendering correctly.

**Comment by bisdavid** [comment]
Ok.  I think it was due to the lack of a space between "Output" and the double-colons.

Does it look ok now?

**Comment by dstufft** [comment]
Almost there I think, I just noticed the For More Information links appear not to be rendering correctly.

**Comment by bisdavid** [comment]
I think I have the links fixed now.  Sorry for the delay - I was out all last week.

**Comment by bisdavid** [comment]
Fixed one additional link issue.

**Pull request merged**
