### PR TITLE
Allow the 5.1 release of pyyaml

### PR DESCRIPTION
**Pull request by asottile**
Similar to #3430

This allows the latest version of pyyaml to be used without conflict

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by asottile** [comment]
@JordonPhillips @dstufft anything I can help with to get this integrated?  awscli is currently preventing us from upgrading pyyaml

**Comment by jessedoyle** [comment]
This is a great change! We use `pipenv` in many projects and GitHub is flagging security vulnerabilities left, right and center everytime `awscli` is specified as a dependency.

What's missing to merge this?

**Comment by asottile** [comment]
@kyleknap maybe you can review this? it's been two months <3

**Comment by kabbedijk** [comment]
Is there any way we can help on getting this merged? If there are things to fix, please let us know.

**Comment by asottile** [comment]
(pinging some other recent approvers) @jamesls @joguSD can you take a look at this?

**Comment by florck** [comment]
Please, can you please review and merge this AWS, all job is made, and waiting this, we have lots of impacts of incompatible dependancies.

**Comment by kabbedijk** [comment]
Has been merged in:
https://github.com/aws/aws-cli/pull/4231

**Comment by dstufft** [comment]
Merged in https://github.com/aws/aws-cli/pull/4231

**Pull request closed without merging**
