### PR TITLE
Add examples for GenerateDataKey* operations

### PR DESCRIPTION
**Pull request by juneb**
*Description of changes:* Ongoing project to improve the quality and coverage of KMS CLI examples. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by juneb** [comment]
Filed the required ticket with aws-docs: https://t.corp.amazon.com/P69076988

**Comment by elysahall** [comment]
Hi June,
Also responded to the ticket. A couple of minor fixes:

- In ``generate-data-key-pair-without-plaintext.rst`` and ``generate-data-key-pair.rst`` in the code example you list ``--key-id`` twice.
``        --key-id --key-id 1234abcd-12ab-34cd-56ef-1234567890ab \``

- In generate-data-key.rst you have multiple examples and are missing the ``Example 1:`` and ``Example 2:`` label.

**Comment by elysahall** [comment]
LGTM!

**Review by kdaily — APPROVED** [review]
LGTM!

**Comment by juneb** [comment]
Any reason for a delay on this PR?

**Comment by kdaily** [comment]
Merged these changes as part of #7254, closing this. Thanks again for the changes!

**Pull request closed without merging**
