### PR TITLE
Increase docutils upper bound to <0.21

### LINKED ISSUE #4837: New docutils 0.16 release goes past pin in awscli and botocore
Docutils latest release (0.16) has [dropped support for 2.6 and 3.4](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-16-2020-01-12), and has gone past the version pinned by awscli and boto3.

### PR DESCRIPTION
**Pull request by tkelman**
*Issue #, if available:* Closes #4837

*Description of changes:* Analogous to #4420. I believe this should be safe now that aws-cli has dropped support for python 3.4? (ref https://docutils.sourceforge.io/HISTORY.html#release-0-16)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kdaily** [comment]
Thanks @tkelman. It looks like 0.17 is still in pre-release. We would need to wait for a final release and then test it out internally.

**Comment by tkelman** [comment]
Correct @kdaily, but I'm keeping it a strict upper bound here, and 0.16 was released Jan 12, 2020. Would you rather bump the strict upper bound by 2 versions later, or do it in two changes?

**Comment by tkelman** [comment]
> Would you rather bump the strict upper bound by 2 versions later, or do it in two changes?

And if it's the latter, does the first change (the current version of this PR) need to wait until the next awscli minor release?

**Comment by tkelman** [comment]
Ping again on this, what's needed to merge? I see the s3transfer dependency bounds (lower too, not just upper) changed minor version during a patch release of awscli.

docutils versions 0.16 (released Jan 12 2020), 0.17 (released Apr 3 2021), and 0.17.1 (released Apr 17 2021) are all blocked by the existing upper bounds.

**Comment by kdaily** [comment]
Hi @tkelman, appreciate you keeping on this. It is in our backlog, but we have not yet reviewed the changes made in `docutils`. I don't have a timeline on when that will happen, unfortunately.

**Comment by asford** [comment]
@nateprewitt @kdaily (from https://github.com/aws/aws-cli/issues/5943 and https://github.com/aws/aws-cli/issues/4837)

Is there anything blocking this dep update?

**Comment by RDCH106** [comment]
> @nateprewitt @kdaily (from #5943 and #4837)
> 
> Is there anything blocking this dep update?

I think there is nothing pending that blocks it.

A dependency that is limited above to a version that was released two years ago is still a problem... 😔

It is also another recent PR with the same change https://github.com/aws/aws-cli/pull/7384

**Comment by stancel** [comment]
+1

**Comment by tkelman** [comment]
Worth noting that #7384 has the advantage that it was auto-generated by dependabot, but that PR is against the v2 branch so it would separately need to be backported to awscli v1.

**Comment by tim-finnigan** [comment]
Closing in favor of newer [dependabot PRs](https://github.com/aws/aws-cli/pulls?q=is%3Aopen+is%3Apr+author%3Aapp%2Fdependabot+docutils).

**Comment by tkelman** [comment]
It looks to me like those dependabot PR's that are against v1 (develop) may need some manual tweaking to also update setup.cfg

**Pull request closed without merging**
