### PR TITLE
add back pyyaml dependency on python 3.3

### PR DESCRIPTION
**Pull request by tkelman**
looks like a logic mistake in https://github.com/aws/aws-cli/commit/b9a62ad07789bad35b6a0c114c451084c3de8efc

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by stealthycoin** [comment]
Looks like dependable merged it because someone approved it before I was done working on it. I have that in my branch: 
https://github.com/stealthycoin/aws-cli/commit/27e53eccef8e250f0862552ac50323df02ed65

But it got merged before that. I guess we should never approve dependabot PRs as there does not appear to be a way to disable that behavior.

**Comment by tkelman** [comment]
Thanks. Looks like you could use `@dependabot cancel merge` to pause the auto-merging behavior while you're working on something. Wonder why it's configured to do "rebase and merge" by default.

**Comment by stealthycoin** [comment]
I think we will just make the develop branch protected so the bot can't merge. Remembering not to merge, or to type dependabot commands seems like someone could easily forget. And from the settings it looks like I could only disable auto-merge AWS org-wide which I'm sure would annoy other teams.

**Comment by jamesls** [comment]
I think we're going to have to modify this slightly.  pyyaml does not support python 3.3 so this will fail if you create a new py3.3 virtualenv and try to install the CLI:

```
$ mktmpenv --python ~/.pythonz/pythons/CPython-3.3.6/bin/python
Running virtualenv with interpreter /Users/jamessar/.pythonz/pythons/CPython-3.3.6/bin/python
Using base prefix '/Users/jamessar/.pythonz/pythons/CPython-3.3.6'
New python executable in /Users/jamessar/.virtualenvs/tmp-ffc600528feb78fe/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/jamessar/.virtualenvs/tmp-ffc600528feb78fe/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/jamessar/.virtualenvs/tmp-ffc600528feb78fe/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/jamessar/.virtualenvs/tmp-ffc600528feb78fe/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/jamessar/.virtualenvs/tmp-ffc600528feb78fe/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/jamessar/.virtualenvs/tmp-ffc600528feb78fe/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-ffc600528feb78fe) ~/.virtualenvs/tmp-ffc600528feb78fe $ pip install awscli
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Collecting awscli
  Using cached https://files.pythonhosted.org/packages/a7/60/ba06ebce4d55be61c1a961bdaff1e6e4ceae6b1babe6c6ee321d9b501e5d/awscli-1.16.257-py2.py3-none-any.whl
Collecting PyYAML<=5.2,>=3.10; python_version != "2.6" (from awscli)
PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

We'll need to drop this version do `<=3.13`:

```
$ pip install 'PyYAML>=3.10,<=5.2'
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Collecting PyYAML<=5.2,>=3.10
PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.



$ pip install 'PyYAML>=3.10,<=3.13'
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Collecting PyYAML<=3.13,>=3.10
  Using cached https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Building wheels for collected packages: PyYAML
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /Users/jamessar/Library/Caches/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
Successfully built PyYAML
Installing collected packages: PyYAML
Successfully installed PyYAML-3.13
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Pull request merged**
