### PR TITLE
[Feature] Add snap build

### LINKED ISSUE #7177: aws v2 as snap package for cpus: arm, arm64, amd64.
### Describe the feature

You have snap package from amazon of aws cli:
https://snapcraft.io/aws-cli

Please update this for v2 and compile for more cpus: arm, arm64 and am64.

I successful compile aws-cli 2 on snap package for arm. 
I can share it with you, also make a package here on the repo. Also make it for the ci.

### Use Case

snap package for arm, arm64, amd64.

### Proposed Solution

snap package. 

### Other Information

_No response_

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2

### Environment details (OS name and version, etc.)

linux.

### PR DESCRIPTION
**Pull request by talregev**
Add snap build.
fix #7177

### CODE REVIEW

**Comment by talregev** [comment]
Please approve my workflow

**Comment by talregev** [comment]
Build and run on vm snap aws-cli:

image

**Comment by talregev** [comment]
Build and run on vm snap package for aws v1.25.47

image

**Comment by tim-finnigan** [comment]
Closing this as noted in https://github.com/aws/aws-cli/issues/7177#issuecomment-1212125627

**Pull request closed without merging**
